#!/usr/bin/env python3
# VERSION: 2026-08-25-go1
"""
go.py -- one command. Runs everything in order, writes one report.

    python research/go.py                       # from C:\\kals
    python research/go.py --quick               # skip the slow null draws
    python research/go.py --only chain          # a single stage

WHAT IT DOES

  1. Every self-test, first. If any fails, the run STOPS and no real data is
     touched. Four bugs of the fake-edge family were caught by these tests in
     two days; they are not a formality.
  2. Then each analysis stage, in dependency order, skipping any whose input
     is missing rather than failing the run.
  3. Writes RESULTS.md with the command, the raw output, and the exit status
     of every stage.

STAGES

  chain     strike(N+1) == settle(N). Gates the contract, and yields a
            15-min-spaced TWAP series per asset from PUBLIC settled records.
            Needs only the internet. Start here.
  volmodel  is the tail fat, or is it vol clustering? Decides which model to
            build. Needs chain_cache.json from the stage above.
  placebo   what does the calibration estimator return when the market IS
            efficient? Makes the existing 450-market result readable.
            Needs fulltape/.
  replay    run the decision engine over recorded collector data and score the
            P&L against its null. Needs kalshi_data/ and fulltape/.
  leadlag   does the book FOLLOW the index? PLAN_V3 ranks this the single most
            likely surviving edge, because it is plumbing rather than opinion.
            Needs kalshi_data/ and fulltape/.

NOTHING HERE PLACES AN ORDER. There is no order code in this repository and no
flag that enables one.
"""

import argparse
import os
import subprocess
import sys
import time
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

SELFTESTS = [
    ("settlement math", ["settlement_math.py"]),
    ("chain harness", ["chain.py", "--selftest"]),
    ("vol discriminator", ["volmodel.py", "--selftest"]),
    ("model-vs-market", ["edge.py", "--selftest"]),
    ("null calibrator", ["placebo.py", "--selftest"]),
    ("decision engine", ["engine.py", "--selftest"]),
    ("replay", ["replay.py", "--selftest"]),
    ("lead-lag", ["leadlag.py", "--selftest"]),
]

# Paths are all relative to the repo root, and every stage runs there, so
# ./chain_cache.json means the same thing to the stage that writes it and the
# stage that reads it.
STAGES = [
    ("chain", ["research/chain.py", "--markets", "5000",
               "--cache", "./chain_cache.json"], None),
    ("volmodel", ["research/volmodel.py", "--cache", "./chain_cache.json"],
     "chain_cache.json"),
    ("placebo", ["research/placebo.py", "--out", "{out}"], "{out}/markets.json"),
    ("replay", ["research/replay.py", "--data", "{data}", "--out", "{out}"],
     "{data}/cfbenchmarks_value"),
    ("leadlag", ["research/leadlag.py", "--data", "{data}", "--out", "{out}"],
     "{data}/cfbenchmarks_value"),
]


def run(cmd, cwd, timeout):
    t0 = time.time()
    try:
        p = subprocess.run([sys.executable] + cmd, cwd=cwd, timeout=timeout,
                           capture_output=True, text=True)
        return p.returncode, (p.stdout or "") + (p.stderr or ""), time.time() - t0
    except subprocess.TimeoutExpired as e:
        out = (e.stdout or b"")
        if isinstance(out, bytes):
            out = out.decode("utf-8", "replace")
        return 124, out + f"\n*** TIMED OUT after {timeout}s ***", time.time() - t0
    except Exception as e:
        return 1, f"*** {type(e).__name__}: {e} ***", time.time() - t0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="./kalshi_data")
    ap.add_argument("--out", default="./fulltape")
    ap.add_argument("--report", default="RESULTS.md")
    ap.add_argument("--only")
    ap.add_argument("--quick", action="store_true")
    ap.add_argument("--skip-selftests", action="store_true",
                    help="not recommended; they exist because this project's "
                         "history is of measurement bugs producing fake edges")
    a = ap.parse_args()

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    chunks = [f"# RESULTS — automated run\n\n`{stamp}`\n",
              "Generated by `research/go.py`. Every stage's raw output is "
              "reproduced verbatim.\n"]
    print("=" * 78)
    print(f"go.py   {stamp}")
    print(f"  cwd={os.getcwd()}  data={a.data}  out={a.out}")
    print("=" * 78)

    ok = True
    if not a.skip_selftests and not a.only:
        print("\nSELF-TESTS (a failure here stops the run)")
        chunks.append("\n## Self-tests\n")
        for name, cmd in SELFTESTS:
            rc, out, dt = run(cmd, HERE, 900)
            passed = (rc == 0)
            ok = ok and passed
            print(f"  {name:>20}  {'PASS' if passed else '*** FAIL ***'}"
                  f"  ({dt:.0f}s)")
            chunks.append(f"\n### {name} — "
                          f"{'PASS' if passed else 'FAIL'} ({dt:.0f}s)\n")
            if not passed:
                chunks.append("```\n" + out[-4000:] + "\n```\n")
                # Show it here too. Burying the reason in the report cost a
                # whole round trip the first time this fired.
                tail = [ln for ln in out.strip().splitlines() if ln.strip()]
                for ln in tail[-6:]:
                    print(f"        | {ln[:110]}")
        if ok:
            os.environ["KALS_SELFTESTED"] = "1"
        if not ok:
            print("\n*** A SELF-TEST FAILED. Stopping; no real data touched. ***")
            print("    The failing output is in the report. Send it back.")
            chunks.append("\n**A self-test failed — no real data was "
                          "analysed.**\n")
            open(os.path.join(ROOT, a.report), "w").write("\n".join(chunks))
            raise SystemExit(1)

    print("\nSTAGES")
    chunks.append("\n## Stages\n")
    for name, cmd, need in STAGES:
        if a.only and a.only != name:
            continue
        cmd = [c.replace("{data}", a.data).replace("{out}", a.out) for c in cmd]
        if need:
            path = need.replace("{data}", a.data).replace("{out}", a.out)
            if not os.path.exists(os.path.join(ROOT, path)) and \
               not os.path.exists(path):
                print(f"  {name:>20}  SKIPPED (missing {path})")
                chunks.append(f"\n### {name} — SKIPPED\n\nMissing `{path}`.\n")
                continue
        if a.quick and name in ("placebo",):
            cmd += ["--reps", "60"]
        rc, out, dt = run(cmd, ROOT, 600 if a.quick else 3600)
        print(f"  {name:>20}  {'ok' if rc == 0 else f'exit {rc}'}  ({dt:.0f}s)")
        chunks.append(f"\n### {name}\n\n```\npython {' '.join(cmd)}\n```\n")
        chunks.append(f"\nexit {rc}, {dt:.0f}s\n\n```\n{out[-60000:]}\n```\n")

    chunks.append("\n## How to read this\n\n"
                  "- `n` is always a number of MARKETS or CLOSE-TIME CLUSTERS, "
                  "never trades.\n"
                  "- A P&L figure means nothing without its null band; the "
                  "replay stage prints both.\n"
                  "- Every large edge this project has produced so far was a "
                  "measurement bug. Treat anything eye-catching as a bug until "
                  "it survives its own null.\n")
    path = os.path.join(ROOT, a.report)
    open(path, "w").write("\n".join(chunks))
    print(f"\nwrote {path}")
    print("Send that file back.")


if __name__ == "__main__":
    main()
